### ISSUE TITLE
bem-object hasn't mod, but has modName

### ISSUE THREAD

**Issue by gitim** [floatdrop/bem-deps#2]
Hello! It seems, that there is a bug in bem-deps. [Here](https://github.com/floatdrop/bem-deps/blob/master/index.js#L68) is getting mod field from [bem-object](https://github.com/floatdrop/bem-object#properties), but it fails, because this field is named [modName](https://github.com/floatdrop/bem-object/blob/master/index.js#L9). Could you fix it?

**Comment by iamstarkov** [comment]
hi, thanks for reporing. [Are you it failing](https://github.com/floatdrop/bem-deps/blob/master/index.js#L18)?

anyway pull-request with failing tests will help a lot

**Comment by gitim** [comment]
I meant `dep.mod`, this is bem-object and it has `modName`, but not `mod`

**Comment by gitim** [comment]
> anyway pull-request with failing tests will help a lot

done
